---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - taintremovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - taintremovers/finalizers
  verbs:
  - update
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - taintremovers/status
  verbs:
  - get
  - patch
  - update
