# permissions for end users to edit taintremovers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: taintremover-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: taint-remover
    app.kubernetes.io/part-of: taint-remover
    app.kubernetes.io/managed-by: kustomize
  name: taintremover-editor-role
rules:
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - taintremovers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodes.peppy-ratio.dev
  resources:
  - taintremovers/status
  verbs:
  - get
