apiVersion: nodes.peppy-ratio.dev/v1alpha1
kind: TaintRemover
metadata:
  labels:
    app.kubernetes.io/name: taintremover
    app.kubernetes.io/instance: taintremover-sample
    app.kubernetes.io/part-of: taint-remover
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: taint-remover
  name: taintremover-sample
spec:
  taints:
  - key: oci.oraclecloud.com/oke-is-preemptible
    effect: NoSchedule
